### ISSUE TITLE
GosuMechanics Yasuo Q Prediction 

### ISSUE THREAD

**Issue by Luc4z** [berbb/PortAIO#232]
When i enable SDKPredition it seems like his Q/Q3 prediction still broken that it will never hit enemy with over 380 move speed  , and even if i turn it off it still broken , hope it can be fix , otherwise this would be the only good one for EB , thanks !

and also targetselector might have some issues , if there's auto locked target like lower health enemy in 1000 range(im not sure but just like in vision , and also didnt active focus select target) , it wont attack another enemy even they're in AA range (also wont cast any spells)

**Comment by inphratiic** [comment]
Regarding the target selector they can't do nothing because it's the EB target selector

**Comment by berbb** [comment]
Fixed Prediction & Removed the Forced Target call.

**Comment by Luc4z** [comment]
holy molly , fast update , ill try it right after , thanks !

**Comment by Luc4z** [comment]
test and still not aiming well tho , like if enemy in 45 degree and moving away from my Yasuo , Q/Q3 will never hit :(

**Comment by berbb** [comment]
Are you using SDKPredictioner still or no?

**Comment by berbb** [comment]
It should be OK now, I just tested and its landing Qs/Q3s.
