### ISSUE TITLE
Valvrave Yasuo - doesn't use E when in lasthit/laneclear mode

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#420]
I enabled it in settings but it's still not used. The script overall, well, feels pretty tough imho. Which one would you guys recommend instead? YasuoPro or?

**Comment by IlikeBaconLol** [comment]
YasuoPro is awesome; try to clear apdata

YasuoPro has insane walldashing

**Comment by Monnq** [comment]
for me every yasuo script is broken and doesn't use spells lmao. tried clearing appdata.

**Comment by IlikeBaconLol** [comment]
Yes try that bcz the issues is from u

**Comment by berbb** [comment]
I'm not sure about the error you're having about not using any spells at all but I fixed the issue with Yasuo on Valvrave not using E.

**Comment by Monnq** [comment]
E now works perfectly fine when lasthiting, but the same bug still occurs with Q which doesn't work in last hiting, could you check it too pls?
